# Generated by Django 5.1.1 on 2024-10-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ART_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ART_NAME', models.CharField(max_length=100)),
                ('ART_FIRSTNAME', models.CharField(max_length=100)),
                ('ART_LASTNAME', models.CharField(max_length=100)),
                ('ART_EMAIL', models.EmailField(max_length=254)),
                ('ART_TEL', models.CharField(max_length=20)),
                ('ART_PASSWORD', models.CharField(max_length=100)),
                ('ART_BIOGRAPHY', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CAT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CAT_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('TAB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TAB_NAME', models.CharField(max_length=100)),
                ('TAB_DESCRIPTION', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EMP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_FIRSTNAME', models.CharField(max_length=100)),
                ('EMP_LASTNAME', models.CharField(max_length=100)),
                ('EMP_EMAIL', models.EmailField(max_length=254)),
                ('EMP_TEL', models.CharField(max_length=20)),
                ('EMP_PASSWORD', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('TYD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TYD_NAME', models.CharField(max_length=100)),
                ('TYD_FORMAT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DOC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DOC_NAME', models.CharField(max_length=100)),
                ('DOC_INFORMATION', models.TextField()),
                ('ART_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('COL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COL_NAME', models.CharField(max_length=100)),
                ('COL_ORDER', models.IntegerField()),
                ('TAB_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.dynamictable')),
                ('TYD_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.typedata')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PRJ_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PRJ_NAME', models.CharField(max_length=100)),
                ('PRJ_FORMAT', models.CharField(max_length=50)),
                ('PRJ_DUE_DATE', models.DateField()),
                ('DOC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.document')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('ROW_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ROW_NAME', models.CharField(max_length=100)),
                ('ROW_ORDER', models.IntegerField()),
                ('TAB_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.dynamictable')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('CEL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CEL_VALUE', models.TextField()),
                ('COL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.column')),
                ('ROW_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.row')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('SUP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SUP_NAME', models.CharField(max_length=100)),
                ('SUP_DURATION', models.DurationField()),
                ('SUP_PROGRESS', models.FloatField()),
                ('CAT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.category')),
                ('PRJ_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.project')),
            ],
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='SUP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.support'),
        ),
    ]
