# Generated by Django 5.1.1 on 2024-11-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamictable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagOption',
            fields=[
                ('TAG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TAG_COLOR', models.CharField(max_length=50)),
                ('TAG_VALUE', models.CharField(max_length=100)),
                ('COL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamictable.column')),
            ],
        ),
    ]
